### ISSUE TITLE
Limit file types for upload

### ISSUE THREAD

**Issue by lutzfischer** [martingraham/searchSubmit#1]
File types (by extension only)
PeakList/Acquisition:

.mgf
.msm
.apl
.zip
Fasta/sequence files:

.fasta
.txt
Capitalisation should be ignored

**Comment by colin-combe** [comment]
Moved this to https://github.com/Rappsilber-Laboratory/searchSubmit/issues/1

close here if you like

**Comment by martingraham** [comment]
shoved over to fork
